### ISSUE TITLE
perl-image-exiftool tool not found in kali linux

### ISSUE THREAD

**Issue by mistrysiddh** [b-m-f/hugo-picture-optimization#3]
I cloned this script and tried to run it and I got this error

```
┌──(root💀MrFoxie)-[/mnt/c/Users/SIDDH/Desktop/hugo/mistrysiddh]
└─# apt install perl-image-exiftool
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package perl-image-exiftool
```

**Comment by b-m-f** [comment]
Hi @mrfoxie 

This is an issue you should ask the folks from Kali.
But I am sure there is just a different name for the tool in their repositories.

**Comment by mistrysiddh** [comment]
okay thank u

**Comment by scillidan** [comment]
@mrfoxie I installed `libimage-exiftool-perl` on Ubuntu.
