### ISSUE TITLE
improving the display of search result

### ISSUE THREAD

**Issue by evanescente-ondine** [b-m-f/hugo-picture-optimization#4]
I noticed the variables .title, used to display the pages in search results, do not have their markdown nor html processed, in the sense that writing \<br> in the .Title is correctly displayed as a linebreak in the menu, but only as "\<br>" in the search result.
I do not know how to correct json/js whatever, could you ? Like, add the equivalent of "| markdownify" to the results ?

Thanks

**Comment by b-m-f** [comment]
Which variable are you talking about?
I think you might want to open this issue on the main hugo repository. In this project there is no code related to markdown/json/js. Purely picture optimization that uses the hugo directory structure

**Comment by evanescente-ondine** [comment]
ahahah, my bad, actually I missed the right github, I was looking hugo-book, my theme. Sorry pal
